# Generated by Django 4.1.6 on 2023-02-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadlines',
            fields=[
                ('dl_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('days', models.IntegerField()),
            ],
            options={
                'db_table': 'deadlines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('userlastname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
